--- isle-imageservices/Dockerfile	2021-04-06 09:53:28.000000000 -0400
+++ Dockerfile	2021-04-06 09:51:58.000000000 -0400
@@ -1,4 +1,5 @@
-FROM islandoracollabgroup/isle-tomcat:1.5.3
+FROM 840783682283.dkr.ecr.us-east-1.amazonaws.com/islandoracollabgroup/isle-tomcat:1.5.3
+
 
 # Set up environmental variables for Tomcat, Cantaloupe & dependencies
 # @see: Cantaloupe https://cantaloupe-project.github.io/
