--- isle-imageservices/Dockerfile	2020-10-23 12:26:02.000000000 -0400
+++ Dockerfile	2020-11-19 12:41:45.000000000 -0500
@@ -1,4 +1,4 @@
-FROM islandoracollabgroup/isle-tomcat:1.5.2
+FROM 840783682283.dkr.ecr.us-east-1.amazonaws.com/islandoracollabgroup/isle-tomcat:1.5.2
 
 # Set up environmental variables for Tomcat, Cantaloupe & dependencies
 # @see: Cantaloupe https://cantaloupe-project.github.io/
